apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: telegramfriend
spec:
  selector:
    matchLabels:
      app: telegramfriend
  replicas: 1
  template:
    metadata:
      labels:
        app: telegramfriend
    spec:
      containers:
      - name: telegramfriend
        image: correiabrux/telegramfriend:1.0
        env:
        - name: newsapikey
          value: "YOURNEWSAPIKEY"
        - name: telegramtoken
          value: "YOURTELEGRAMKEY"          
